services:
  - type: web
    name: url-shortener-api
    runtime: node
    plan: free
    region: singapore
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
